server:
  port: 8082
spring:
  datasource:
    driver-class-title: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/photop
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    mode: HTML5
logging:
  config: classpath:logback.xml
  path: /home/project/photop/log
